"""Added Order table-2

Revision ID: 04de13eaa09b
Revises: 01018d59c70a
Create Date: 2025-05-10 20:29:17.290587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "04de13eaa09b"
down_revision: Union[str, None] = "01018d59c70a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("payment_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "payment_status",
            sa.Enum("PENDING", "CONFIRMED", "REJECTED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("delivery_location", sa.JSON(), nullable=True),
        sa.Column("shipping_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tracking_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("estimated_delivery", sa.DateTime(), nullable=True),
        sa.Column("discount_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("discount_amount", sa.Float(), nullable=False),
        sa.Column("subtotal", sa.Float(), nullable=False),
        sa.Column("tax_amount", sa.Float(), nullable=False),
        sa.Column("shipping_cost", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shopper_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "CONCLUDED", "CANCELLED", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shopper_id"],
            ["shopper.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orderitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orderitem")
    op.drop_table("order")
    # ### end Alembic commands ###
