"""Added Product and Vendor relationship; added missing discount_rate property on Product

Revision ID: 439feff79d62
Revises: 11a76a14da0b
Create Date: 2025-05-09 14:16:38.068570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439feff79d62'
down_revision: Union[str, None] = '11a76a14da0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discount_percentage')
    # ### end Alembic commands ###
