"""Added shopping_cart property on Shopper

Revision ID: f20b2c275e16
Revises: 04de13eaa09b
Create Date: 2025-05-13 21:45:08.278824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20b2c275e16'
down_revision: Union[str, None] = '04de13eaa09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopper', sa.Column('shopping_cart', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopper', 'shopping_cart')
    # ### end Alembic commands ###
